#
# For reference: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#

Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing

Layout/IndentationConsistency:
  EnforcedStyle: rails
  SupportedStyles:
    - normal
    - rails

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
  SupportedStyles:
    - require_no_space
    - require_space

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: true
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/TrailingCommaInLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last item of all
  # non-empty array and hash literals.
  EnforcedStyleForMultiline: consistent_comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/EmptyLiteral:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  SupportedStyles:
    - assign_to_condition
    - assign_inside_condition

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
    '%': '{}'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact
  Enabled: false

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  CountComments: false
  Max: 100
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 100
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Max: 100
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  ExcludedMethods: []
  Enabled: false

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15
  Enabled: false
